### ISSUE TITLE
add "powered by " to the footer

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/DAOwidget#15]
- [x] добавиь в футер `Powered by <a href="https://tools.onout.org/dao">OnOut - no-code tool to create DAO</a>`

- [x] добавить опцию hideServiceLink = false;

**Comment by noxonsu** [comment]
связано https://github.com/noxonsu/tools.onout.org/issues/10 

так же подумать, куда добавить ссылки на этот тул по интернету. например amazing dao tools https://www.google.com/search?q=github+awesome++dao+tools&newwindow=1&sxsrf=APq-WBtqDcqffKRCJzsShEA9nEaAmbaiuw%3A1643895045185&ei=Bdn7YanfCqGVxc8P3JeQ0Aw&ved=0ahUKEwjp9dyh0uP1AhWhSvEDHdwLBMoQ4dUDCA4&uact=5&oq=github+awesome++dao+tools&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsAM6AggASgQIQRgASgQIRhgAUJ0CWOQKYJwMaAJwAngBgAHUAYgBgAiSAQUzLjQuMZgBAKABAcgBCMABAQ&sclient=gws-wiz

**Comment by VitaliyShulik** [comment]
<img width="784" alt="Screen Shot 2022-02-05 at 15 11 13" src="https://user-images.githubusercontent.com/36531102/152635942-f1c650e2-f74b-48ba-aee0-55e50994b7c0.png">
<img width="700" alt="Screen Shot 2022-02-05 at 15 11 26" src="https://user-images.githubusercontent.com/36531102/152635945-2e284e7c-a016-4a89-b949-fe0995240462.png">
<img width="444" alt="Screen Shot 2022-02-05 at 15 12 05" src="https://user-images.githubusercontent.com/36531102/152635946-de2d0b19-2e63-4cab-85a5-6c5e6abcc3f8.png">

**Comment by noxonsu** [comment]
data-hide-service-link="true"

**Comment by VitaliyShulik** [comment]
https://github.com/noxonsu/tools.onout.org/pull/13
